# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\project\python\finapp2\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1438, 783)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #001f3f;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', \'Arial\', sans-serif;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #002f5f;\n"
"    border: 1px solid #00ff00;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"    border: 1px solid #00ff00;\n"
"    font-family: \'Consolas\', \'Courier New\', monospace;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border-bottom: 1px solid #00ff00;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    width: 15px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #00ff00;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.metricsView = QtWidgets.QColumnView(self.centralwidget)
        self.metricsView.setEnabled(True)
        self.metricsView.setObjectName("metricsView")
        self.gridLayout.addWidget(self.metricsView, 7, 0, 1, 6)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.overviewTab = QtWidgets.QWidget()
        self.overviewTab.setObjectName("overviewTab")
        self.tabWidget.addTab(self.overviewTab, "")
        self.metricsView1 = QtWidgets.QWidget()
        self.metricsView1.setObjectName("metricsView1")
        self.tabWidget.addTab(self.metricsView1, "")
        self.chart1View = QtWidgets.QWidget()
        self.chart1View.setObjectName("chart1View")
        self.tabWidget.addTab(self.chart1View, "")
        self.chart2Tab = QtWidgets.QWidget()
        self.chart2Tab.setObjectName("chart2Tab")
        self.tabWidget.addTab(self.chart2Tab, "")
        self.gridLayout.addWidget(self.tabWidget, 5, 0, 1, 6)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 0, 1, 1, 1)
        self.australiaLabel = QtWidgets.QLabel(self.centralwidget)
        self.australiaLabel.setObjectName("australiaLabel")
        self.gridLayout.addWidget(self.australiaLabel, 1, 1, 1, 1)
        self.germanyLabel = QtWidgets.QLabel(self.centralwidget)
        self.germanyLabel.setObjectName("germanyLabel")
        self.gridLayout.addWidget(self.germanyLabel, 1, 2, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 0, 1, 1)
        self.newyorkLabel = QtWidgets.QLabel(self.centralwidget)
        self.newyorkLabel.setObjectName("newyorkLabel")
        self.gridLayout.addWidget(self.newyorkLabel, 1, 4, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout.addWidget(self.lcdNumber_3, 0, 2, 1, 1)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout.addWidget(self.lcdNumber_4, 0, 3, 1, 1)
        self.startDateLabel = QtWidgets.QLabel(self.centralwidget)
        self.startDateLabel.setStyleSheet("QMainWindow {\n"
"    background-color: #001f3f;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', \'Arial\', sans-serif;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #002f5f;\n"
"    border: 1px solid #00ff00;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"    border: 1px solid #00ff00;\n"
"    font-family: \'Consolas\', \'Courier New\', monospace;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border-bottom: 1px solid #00ff00;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    width: 15px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #00ff00;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"")
        self.startDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startDateLabel.setObjectName("startDateLabel")
        self.gridLayout.addWidget(self.startDateLabel, 3, 0, 1, 1)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.gridLayout.addWidget(self.lcdNumber_5, 0, 4, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setStyleSheet("QMainWindow {\n"
"    background-color: #001f3f;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', \'Arial\', sans-serif;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #002f5f;\n"
"    border: 1px solid #00ff00;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"    border: 1px solid #00ff00;\n"
"    font-family: \'Consolas\', \'Courier New\', monospace;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border-bottom: 1px solid #00ff00;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    width: 15px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #00ff00;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"")
        self.dateEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 1, 1, 2)
        self.londonLabel = QtWidgets.QLabel(self.centralwidget)
        self.londonLabel.setObjectName("londonLabel")
        self.gridLayout.addWidget(self.londonLabel, 1, 3, 1, 1)
        self.sanfransiscoLabel = QtWidgets.QLabel(self.centralwidget)
        self.sanfransiscoLabel.setObjectName("sanfransiscoLabel")
        self.gridLayout.addWidget(self.sanfransiscoLabel, 1, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(1516, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 6)
        self.sectorComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.sectorComboBox.setStyleSheet("QMainWindow {\n"
"    background-color: #001f3f;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', \'Arial\', sans-serif;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #002f5f;\n"
"    border: 1px solid #00ff00;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"    border: 1px solid #00ff00;\n"
"    font-family: \'Consolas\', \'Courier New\', monospace;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border-bottom: 1px solid #00ff00;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    width: 15px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #00ff00;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"")
        self.sectorComboBox.setCurrentText("")
        self.sectorComboBox.setObjectName("sectorComboBox")
        self.gridLayout.addWidget(self.sectorComboBox, 4, 1, 1, 2)
        self.tradesView = QtWidgets.QColumnView(self.centralwidget)
        self.tradesView.setObjectName("tradesView")
        self.gridLayout.addWidget(self.tradesView, 8, 0, 1, 6)
        self.endDateLabel = QtWidgets.QLabel(self.centralwidget)
        self.endDateLabel.setStyleSheet("QMainWindow {\n"
"    background-color: #001f3f;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', \'Arial\', sans-serif;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #002f5f;\n"
"    border: 1px solid #00ff00;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"    border: 1px solid #00ff00;\n"
"    font-family: \'Consolas\', \'Courier New\', monospace;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border-bottom: 1px solid #00ff00;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    width: 15px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #00ff00;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"")
        self.endDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.endDateLabel.setObjectName("endDateLabel")
        self.gridLayout.addWidget(self.endDateLabel, 3, 3, 1, 1)
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.gridLayout.addWidget(self.lcdNumber_6, 0, 5, 1, 1)
        self.japanLabel = QtWidgets.QLabel(self.centralwidget)
        self.japanLabel.setObjectName("japanLabel")
        self.gridLayout.addWidget(self.japanLabel, 1, 0, 1, 1)
        self.sectorLabel = QtWidgets.QLabel(self.centralwidget)
        self.sectorLabel.setStyleSheet("QMainWindow {\n"
"    background-color: #001f3f;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', \'Arial\', sans-serif;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #002f5f;\n"
"    border: 1px solid #00ff00;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"    border: 1px solid #00ff00;\n"
"    font-family: \'Consolas\', \'Courier New\', monospace;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border-bottom: 1px solid #00ff00;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    width: 15px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #00ff00;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"")
        self.sectorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sectorLabel.setObjectName("sectorLabel")
        self.gridLayout.addWidget(self.sectorLabel, 4, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setStyleSheet("QMainWindow {\n"
"    background-color: #001f3f;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', \'Arial\', sans-serif;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #002f5f;\n"
"    border: 1px solid #00ff00;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"    border: 1px solid #00ff00;\n"
"    font-family: \'Consolas\', \'Courier New\', monospace;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border-bottom: 1px solid #00ff00;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    width: 15px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #00ff00;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #00ff00;\n"
"    background: #001f3f;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #001f3f;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #00ff00;\n"
"    color: #001f3f;\n"
"}\n"
"")
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 3, 4, 1, 2)
        self.marketComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.marketComboBox.setObjectName("marketComboBox")
        self.gridLayout.addWidget(self.marketComboBox, 4, 4, 1, 2)
        self.marketLabel = QtWidgets.QLabel(self.centralwidget)
        self.marketLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.marketLabel.setObjectName("marketLabel")
        self.gridLayout.addWidget(self.marketLabel, 4, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(1516, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1438, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionDelete_File = QtWidgets.QAction(MainWindow)
        self.actionDelete_File.setObjectName("actionDelete_File")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.actionUpdate)
        self.menuFile.addAction(self.actionDelete_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionVersion)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overviewTab), _translate("MainWindow", "Overview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.metricsView1), _translate("MainWindow", "Metrics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chart1View), _translate("MainWindow", "Chart1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chart2Tab), _translate("MainWindow", "Chart2"))
        self.australiaLabel.setText(_translate("MainWindow", "Australia"))
        self.germanyLabel.setText(_translate("MainWindow", "Germany"))
        self.newyorkLabel.setText(_translate("MainWindow", "New York"))
        self.startDateLabel.setText(_translate("MainWindow", "Start Date"))
        self.londonLabel.setText(_translate("MainWindow", "London"))
        self.sanfransiscoLabel.setText(_translate("MainWindow", "San Fransico"))
        self.endDateLabel.setText(_translate("MainWindow", "End Date"))
        self.japanLabel.setText(_translate("MainWindow", "Japan"))
        self.sectorLabel.setText(_translate("MainWindow", "Sector"))
        self.marketLabel.setText(_translate("MainWindow", "Market"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))
        self.actionDelete_File.setText(_translate("MainWindow", "Delete File"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
